version: 2
updates:
  # For npm/Yarn (uses npm ecosystem)
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json and yarn.lock
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # For GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow YAML files
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
